### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by PrajjwalDatir** [AlenSaito1/wa-sticker-formatter#12]
Here in this Function
https://github.com/AlenSaito1/wa-sticker-formatter/blob/b4eb0685dd3548d08845197cb9e1c7118ed79c88/src/lib/convert.ts#L8

Following Code Uses Recursion. I don't exactly understand, what it's doing but this might be the source of infinite `ffmpeg` loop
```javascript
const convert = async (data: Buffer, mime: string, type: 'crop' | 'full' | 'default' = 'default'): Promise<Buffer> => {
    const isVideo = mime.startsWith('video')
    const image = isVideo ? await videoToGif(data) : data
    if ((isVideo || mime.includes('gif')) && type === 'crop') {
        const filename = `${tmpdir()}/${Math.random().toString(36)}.webp`
        await writeFile(filename, image)
        return convert(await crop(filename), 'image/webp', 'default')
    }
```

**Comment by AlenSaito1** [comment]
It only does it one time. Its purpose is to convert and compress the file into `WebP` using sharp

**Comment by PrajjwalDatir** [comment]
Doesn't it tries to `convert` to webp till it's done in recursive manner?

Won't it create the infinite loop If the compression of gif to webp fails everytime.

**Comment by PrajjwalDatir** [comment]
Ok Cool. It won't go on loop
