### ISSUE TITLE
Remove the libwebp binaries

### ISSUE THREAD

**Issue by AlenSaito1** [AlenSaito1/wa-sticker-formatter#3]
# TODO
- [x] Remove the libwebp binaries 
- [ ] Add a postInstall script which downloads the binaries based on the system

**Comment by PurpShell** [comment]
HEY!

**Comment by PurpShell** [comment]
You can use node-webpmux for exif, a re-implementation of webpmux in pure CommonJS. 

And use sharp for image conversion since it is maintained. 

https://github.com/lovell/sharp/
https://github.com/ApeironTsuka/node-webpmux

**Comment by Nurutomo** [comment]
You can use [node-webpmux](https://github.com/ApeironTsuka/node-webpmux/)

**Comment by AlenSaito1** [comment]
Thanks for the suggestion @Nurutomo. fixed in [`4b7f1d1`](https://github.com/AlenSaito1/wa-sticker-formatter/tree/4b7f1d1051bdbf9cde442856bef2ed282a390c8f)
