### ISSUE TITLE
WebpMux error on termux - Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by guiguicdd** [AlenSaito1/wa-sticker-formatter#5]
I'm running this piece of code in my script that creates a WebP to send to someone as a sticker.

`const webpWithMetadata = await WSF.setMetadata('O melhor robo', 'Jarvis', ran) //returns the webp buffer with metadata`

But when I run this code I get this error: 

![errowebpmux](https://user-images.githubusercontent.com/50055027/122267742-a3593d80-ceb1-11eb-9e38-8f37073a7f67.jpg)

PS: I'm using termux on my android phone...

**Comment by AlenSaito1** [comment]
Sorry for the late Reply, If you're still using WSF, please update to 4.x and use one of the exports (`createSicker()` or `Sticker`)

**Comment by guiguicdd** [comment]
Nice! Don't worry 😁 thank you
