### ISSUE TITLE
Crop problem in still Images

### ISSUE THREAD

**Issue by ni3mumbaikar** [AlenSaito1/wa-sticker-formatter#7]
I checked cropping static Image with `new WSF.Sticker(buffer,{crop: true});` the Image was stretched and same when used with `animated:true` for gifs sticker returned with perfectly centerCropped Image. 
   
`crop:true` is stretching/squeezing static Images and centerCropping gifs I need to centerCrop static images too any workaround to achieve this ?

**Comment by AlenSaito1** [comment]
This has been fixed in 4.x. You can now achieve this with 

```TS
new WSF.Sticker(buffer, {
    type: 'crop'
})
```

**Comment by ni3mumbaikar** [comment]
Solved thanks @AlenSaito1  !
